<a href="https://colab.research.google.com/github/Pushpendra123-0/E-commerce-Dashboard/blob/main/Pandas_Advanced_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [5]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [6]:
a = pd.Series([ 100, 200, 300, 400])

Print a, and data type

In [7]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [8]:
a[2]

np.int64(300)

What are the values of index for series a?

In [9]:
pd.Series([0,1,2,3])

0    0
1    1
2    2
3    3
dtype: int64

Change the index to  ['c', 'a', 'b', 'd']

In [10]:


my_var=pd.Series([100,200,300,400],index=['c','a','b','d'])
print(my_var)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [11]:

my_var['d']

np.int64(400)

Sort the values wrt to the index and print it

In [12]:


my_var.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [13]:
b = pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [14]:
a = pd.Series([ 100, 200, 300, 400])
b = pd.Series([800,450,100],index=['e','f','g'])
result=pd.concat([a,b])

In [15]:
#print a again after appending b into it

print(result)

0    100
1    200
2    300
3    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [16]:
a = a.sort_values(ascending=False)
print(a)
print(a.index)

3    400
2    300
1    200
0    100
dtype: int64
Index([3, 2, 1, 0], dtype='int64')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [17]:
df = pd.DataFrame(a)
print(df)

#

     0
3  400
2  300
1  200
0  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [18]:

print(df.shape)

(4, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [19]:
# yep its same as the series.
print(df.index)

Index([3, 2, 1, 0], dtype='int64')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [20]:
print(df.head())
print(df.tail())

     0
3  400
2  300
1  200
0  100
     0
3  400
2  300
1  200
0  100

Rename the column of the dataframe as 'points'

In [21]:
df.columns = ['points']
print(df)

   points
3     400
2     300
1     200
0     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [22]:
#Create fruits array

fruits = np.random.choice(['orange','mango','apple'],7)
print(fruits)

['mango' 'orange' 'orange' 'orange' 'orange' 'orange' 'apple']

In [23]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits)
print(fruits)

0     mango
1    orange
2    orange
3    orange
4    orange
5    orange
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [24]:
fruits = fruits.head(len(df))
fruits.index = df.index
print(fruits)

3     mango
2    orange
1    orange
0    orange
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [25]:
df['fruits'] = fruits
print(df.head())

   points  fruits
3     400   mango
2     300  orange
1     200  orange
0     100  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [26]:
d1 = pd.DataFrame({'city':['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],'Temperature':[15, 22, 20, 26,-2]})

Print(d1)

In [27]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [28]:
d1.shape

(5, 2)

Set city = d1['city']

In [29]:
city = d1['city']

print city <br>
What is the type of city.

In [30]:

type(city)

pandas.core.series.Series

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [31]:
d2 = pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],'Temperature':[24,35,36,39]})
print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [32]:

d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [42]:
d3 = pd.concat([d1,d2])
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [34]:
cities_le_20 = d3[d3['Temperature'] <= 20]
print(cities_le_20)
print(f"Number of cities with temperature less than or equal to 20: {len(cities_le_20)}")

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities with temperature less than or equal to 20: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [35]:
cities_ge_35 = d3[d3['Temperature'] >= 35]
print(cities_ge_35)

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [43]:
def is_ut(city_name):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return city_name in union_territories

d3['is_ut'] = d3['city'].apply(is_ut)

In [47]:
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [37]:
def c_to_f(celsius_temp):
    return (celsius_temp * 9/5) + 32

In [38]:
print(c_to_f(10))

50.0

In [44]:
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [45]:
ut_cities = d3[d3['is_ut'] == True]
print(ut_cities)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
3  Pondicherry           39   True           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [55]:
cities_90 = d3[d3['temp_farenhiet'] > 90]
print(cities_90)

          city  Temperature  is_ut  temp_farenhiet
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [56]:
three_rows = d1.head(3)
print(three_rows)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [57]:
all_rows = d3.iloc[:, -2:]
print(all_rows)

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
0  False            75.2
1  False            95.0
2  False            96.8
3   True           102.2

## Groupby

In [49]:
# Create a dataframe using dictionary of your choice

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']}

df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo
4      Eve   45    Sydney

In [58]:
grouped_city = df.groupby('City')['Age'].sum()
print(grouped_city)

City
London      30
New York    25
Paris       35
Sydney      45
Tokyo       40
Name: Age, dtype: int64

In [59]:
grouped_count = df.groupby('City').size()
print(grouped_count)

City
London      1
New York    1
Paris       1
Sydney      1
Tokyo       1
dtype: int64

In [60]:
grouped_min_max = df.groupby('City')['Age'].agg(['min', 'max'])
print(grouped_min_max)

          min  max
City
London     30   30
New York   25   25
Paris      35   35
Sydney     45   45
Tokyo      40   40

In [61]:
grouped_mean = df.groupby(['City', 'Name'])['Age'].mean()
print(grouped_mean)

City      Name
London    Bob        30.0
New York  Alice      25.0
Paris     Charlie    35.0
Sydney    Eve        45.0
Tokyo     David      40.0
Name: Age, dtype: float64

In [62]:
grouped_city_min_max = df.groupby(['City', 'Name'])['Age'].agg(['min', 'max'])
print(grouped_city_min_max)

                  min  max
City     Name
London   Bob       30   30
New York Alice     25   25
Paris    Charlie   35   35
Sydney   Eve       45   45
Tokyo    David     40   40